stages:
  - deploy

before_script:
  - /bin/bash #open a shell
  - apt-get install unzip #install the unzip command for later in the script
  - git clone https://github.com/quarto-dev/quarto-cli #clone the quarto-cli repo
  - cd quarto-cli #switch directories
  - git pull #update to latest development version
  - ./configure.sh #run the installation script for quarto-cli
  
variables:
  QUARTO_PUBLISH_TOKEN: $QUARTO_PUB_AUTH_TOKEN  # Set this variable in GitLab CI/CD settings
  QUARTO_PUBLISH_PROJECT: madc-learning-resource-library  # Replace with your Quarto project name

deploy:
  stage: deploy
  script:
    # Publish your Quarto book using the Quarto CLI
    - quarto install tinytex #install tinytext for publishing to quarto-pub
    - quarto publish --no-prompt --no-browser --token $QUARTO_PUB_AUTH_TOKEN quarto-pub #publish to quarto pub
  only:
    - main  # Deploy only when changes are pushed to the master branch
  tags:
    - shared
