stages:
  - publish

variables:
  QUARTO_PUBLISH_TOKEN: $QUARTO_PUB_AUTH_TOKEN  # Set this variable in GitLab CI/CD settings
  QUARTO_PUBLISH_PROJECT: madc-learning-resource-library  # Replace with your Quarto project name
    
    
quarto_publish:
  stage: publish
  script:
    - apt-get update && apt-get install -y quarto
    - quarto publish quarto-pub --no-prompt --no-browser
  tags:
    - shared