stages:
  - deploy

before_script:
  - /bin/bash
  - apt-get update && apt-get install -y curl
  - curl -L https://github.com/quarto-dev/quarto-cli/releases/latest/download/install.sh | sh
  
variables:
  QUARTO_PUBLISH_TOKEN: $QUARTO_PUB_AUTH_TOKEN  # Set this variable in GitLab CI/CD settings
  QUARTO_PUBLISH_PROJECT: madc-learning-resource-library  # Replace with your Quarto project name


deploy:
  stage: deploy
  script:
    # Publish your Quarto book using the Quarto CLI
    quarto publish quarto-pub
  only:
    - main  # Deploy only when changes are pushed to the master branch
  tags:
    - shared
