stages:
  - setup
  - build
  - publish   
  
variables:
  QUARTO_PUBLISH_TOKEN: $QUARTO_PUB_AUTH_TOKEN  # Set this variable in GitLab CI/CD settings
  QUARTO_PUBLISH_PROJECT: madc-learning-resource-library  # Replace with your Quarto project name

setup_quarto:
  stage: setup
  image: quarto/quarto-cli:latest
  script:
    - quarto --version  # Check the Quarto version for verification
    - quarto init       # Initialize a Quarto project (optional)
  
build_document:
  stage: build
  script:
    - quarto build      # Build your Quarto document
  only:
    - main             # This job will only run on the 'main' branch
    
quarto_publish:
  stage: publish
  script:
    - apt-get update && apt-get install -y quarto
    - quarto publish quarto-pub --no-prompt --no-browser
  tags:
    - shared