image: google/cloud-sdk:latest

stages:
  - deploy

before_script:
  - apt-get update && apt-get install -y unzip git bash # Install necessary packages
  - git clone https://github.com/quarto-dev/quarto-cli # Clone the quarto-cli repo
  - cd quarto-cli # Switch directories
  - git pull # Update to latest development version
  - ./configure.sh # Run the installation script for quarto-cli

deploy:
  stage: deploy
  script:
    # Publish Quarto book using the Quarto CLI
    - quarto install tinytex # Install tinytex for publishing to quarto-pub
    - export QUARTO_PUB_AUTH_TOKEN=$QUARTO_PUB_AUTH_TOKEN # Authentication code environmental variable
    - quarto publish --no-prompt --no-browser quarto-pub # Publish to quarto pub
  only:
    - main  # Deploy only when changes are pushed to the main branch
  tags:
    - shared
