stages:
  - setup
  - publish   
  
variables:
  QUARTO_PUBLISH_TOKEN: $QUARTO_PUB_AUTH_TOKEN  # Set this variable in GitLab CI/CD settings
  QUARTO_PUBLISH_PROJECT: madc-learning-resource-library  # Replace with your Quarto project name
  
image: rocker/r-ver:4.1.1

setup_quarto:
  stage: setup
  image: rocker/r-ver:4.1.1  # Use an R-compatible Docker image
  script:
    - R -e "install.packages('quarto', repos='https://cran.rstudio.com')"
  tags:
    - shared
    
quarto_publish:
  stage: publish
  script:
    - quarto publish quarto-pub --no-prompt --no-browser
  tags:
    - shared