stages:
  - deploy

variables:
  QUARTO_PUBLISH_TOKEN: $QUARTO_PUB_AUTH_TOKEN  # Set this variable in GitLab CI/CD settings
  QUARTO_PUBLISH_PROJECT: madc-learning-resource-library  # Replace with your Quarto project name

deploy:
  stage: deploy
  only:
    - main
  script:
    - export $QUARTO_PUB_AUTH_TOKEN
    - quarto publish quarto-pub  # Publish the Quarto publication
  tags:
    - shared
    