project:
  type: book

book:
  title: "MADC Learning Resource Library"
  author: "Miranda Cooper, Data Analyst / Programmer"
  date: "10/12/2023"
  chapters:
    - index.qmd
    - citation.qmd
    - command.qmd
    - git.qmd
    - generative_ai.qmd
    - m365.qmd
    - python.qmd
    - rstud.qmd
    - regex.qmd
    - sql.qmd
    - stats.qmd
    - tableau.qmd
    - techdoc.qmd
  downloads: pdf
  back-to-top-navigation: true
    
cover-image: cover.png

format:
  html:
    theme: cosmo
    date-modified: today
  pdf:
    documentclass: scrreprt

editor: visual

