**Skill Level**: ★ Beginner --- ★★ Intermediate --- ★★★ Advanced

# 💻 Command-line Interface (CLI)

## Learn the Command-line

#### [**Command Line for Beginners -- How to Use the Terminal Like a Pro**](https://www.freecodecamp.org/news/command-line-for-beginners/) **- Article ★**

> An article from [freeCodeCamp](https://www.freecodecamp.org/news) that explains the various parts of the command line interface and the basics of how it works

#### [**The Linux Command Line**](https://linuxcommand.org/tlcl.php) **- Book ★**

> A book, written with the new command line user in mind, which includes the basics of command line use and shell scripting. Check out the corresponding website: [linuxcommand.org](https://linuxcommand.org/index.php)

#### [**The Art of Command Line**](https://github.com/jlevy/the-art-of-command-line#the-art-of-command-line) **- Guide ★★**

> A guide that provides an overview of interactive Bash for Linux with two sections that include additional guidance for macOS and Windows users

#### [**Command Line Fundamentals**](https://learning.oreilly.com/library/view/command-line-fundamentals/9781789807769/) **- Book ★**

> Master shell basics and Unix tools and discover easy commands to perform complex tasks with speed

## Command-line Tools

#### [**Tabiew**](https://github.com/shshemi/tabiew#tabiew) **- Tool ★★**

> Tabiew is a lightweight, terminal-based application to view and query delimiter separated value formatted documents, such as CSV and TSV files

#### [**emphatic**](https://github.com/coolbutuseless/emphatic/?tab=readme-ov-file#emphatic) **- Tool ★★**

> `{emphatic}` is a tool for exploratory analysis of tabular data. It allows the user to visually colour elements of the data, yet still keep all values visible
