**Skill Level**: ★ Beginner --- ★★ Intermediate --- ★★★ Advanced

# ❔ Structured Query Language (SQL)

## Learn SQL

#### [**SQL Tutorial**](https://www.w3schools.com/sql/default.asp) **- Tutorial ★**

> A self-paced tutorial, by [w3schools](https://www.w3schools.com/), that walks through basic SQL commands

#### [**SQL Keywords Reference**](https://www.w3schools.com/sql/sql_ref_keywords.asp) **- Reference ★**

> A quick reference list of the reserved words in SQL

#### [**SQLZoo Tutorial**](https://sqlzoo.net/wiki/SQL_Tutorial) **- Tutorial ★**

> A step by step tutorial reviewing the basics of SQL queries

#### [**Practical SQL, 2nd Edition**](https://learning.oreilly.com/library/view/practical-sql-2nd/9781098129866/) **- Book ★**

> An approachable and fast-paced guide to SQL (Structured Query Language), the standard programming language for defining, organizing, and exploring data in relational databases

#### [**Learn SQL**](https://www.codecademy.com/learn/learn-sql) **- Course ★**

> A free self-paced course, developed by [codecademy](https://www.codecademy.com/), which demonstrates how to manage large datasets and analyze real data using standard data management language

#### [**SQLBolt: Introduction to SQL**](https://sqlbolt.com/) **- Course ★**

> A series of interactive lessons and exercises designed to help you quickly learn SQL in your browser

#### [**SQL join flavors**](https://antonz.org/sql-join/?utm_campaign=Data_Elixir&utm_source=Data_Elixir_453) **- Article ★★**

> An article that explores various types of SQL joins, including helpful visualizations for each

#### [**SQL for the Weary**](https://gvwilson.github.io/sql-tutorial/) **- Tutorial ★★**

> A tutorial with notes and working examples for various SQL and database functions

#### [**SQL Style Guide**](https://www.sqlstyle.guide/) **- Reference ★**

> A SQL syntax guide designed to be compatible with Joe Celko's [SQL Programming Style](https://www.amazon.com/gp/product/0120887975/ref=as_li_ss_tl?ie=UTF8&linkCode=ll1&tag=treffynnon-20&linkId=9c88eac8cd420e979675c815771313d5) book

## Helpful Tools

#### [**SQL Polyglot**](https://codapi.org/sql/) **- Tool ★★**

> A browser-based tool for checking if a particular SQL feature is supported in various database systems
