name: Dry-Run Deploy to Quarto Pub

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  deploy:
    name: Dry-Run Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up the environment
        run: |
          sudo apt-get update && sudo apt-get install -y unzip git bash

      - name: Clone Quarto CLI repository
        run: |
          git clone https://github.com/quarto-dev/quarto-cli
          cd quarto-cli
          git pull
          ./configure.sh

      - name: Install TinyTeX
        run: |
          quarto install tinytex

      - name: Set up Quarto Pub token (Dry-Run Only)
        run: echo "Simulating token setup for dry-run deployment"
        env:
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}

      - name: Simulate Publishing
        run: |
          echo "Dry-run: Simulating quarto publish command"
          echo "Would execute: quarto publish --no-prompt --no-browser quarto-pub"
